### ISSUE TITLE
Reports an ambiguous message when lcov.info isn't found

### ISSUE THREAD

**Issue by AngryLawyer** [mattjmorrison/grunt-karma-coveralls#3]
If you set coverage_dir to somewhere that doesn't have the lcov.info in it, you get the following:

```
Warning: path must be a string Use --force to continue.
```

I think this is because lcov_path is being set to undefined, and isn't being checked before being fed to the rest of the system.

It'd probably be a good idea to catch this, and provide a friendlier message.

**Comment by Skillnter** [comment]
> This is fixed in `2.2.0`. You should now see something along the lines of:
> 
> ```
> lcov.info not found in `./your/directory/path/here`
> ```

how to get this lcov.info file? its not specified in docs
